version: '3'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: "unless-stopped"
    volumes:
      - ./ollama:/root/.ollama
    # ports:
    #   - "11434:11434"
    expose:
      - "11434"
  openwebui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: always
    volumes:
      - ./ollama-webui:/app/backend/data
    ports:
      - "50890:8080"
    environment:
      - OLLAMA_BASE_URL = "ollama"

  